### ISSUE TITLE
KappNav needs to run on OCP 4.2 and be managed by OLM

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#100]
The KappNav operator needs to run on OCP 4.2, which includes OLM management.  This is a placeholder dependency for the Kappnav project.

**Comment by cvignola** [comment]
@stephenkinder @kaczyns Steve, the OCP 4.2 part I expected and is in progress.  We are planning it for kAppNav 0.1.2, which we're cutting this week for inclusion in Kabanero 0.3.0.  

When Tim and I spoke about operators, we reasoned kAppNav does not need to be under OLM management - at least not for the time being - because it is installed by Kabanero.  Has something changed?

**Comment by stephenkinder** [comment]
@cvignola the issue was opened as a general requirement as it was believed we would need the kAppNav operator to be OLM managed to address our requirements.  It looks to me like @kaczyns and yourself have teased apart the `OCP 4.2` and `OLM` requirements.   I agree that the two requirements can be handled separately and that we can address OLM management in later releases.  I'm going to defer opening a separate issue until the kAppNav project chooses to be managed by OLM, and Kabanero will do the integration work at that time.

I think we can close this issue when kAppNav 0.2.1 delivers.

**Comment by cvignola** [comment]
The kAppNav images for OCP 4.2 are version 0.1.2.  These are delivered.  Regarding OLM, the current decision is to not publish the kAppNav operator there.  I believe this issue can be closed.
