### ISSUE TITLE
Provide Secure Endpoints - Phase 2 (Design)

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#123]
Kabanero should ensure that all networking between components can be over secure protocols.

**Comment by marikaj123** [comment]
No docs required.

**Comment by marikaj123** [comment]
Are we planning to provide the three endpoints for Kabanero v0.6.0? Ans: Yes
@chunlongliang-ibm - Please create the three child issues and link them to this Epic.
This feature may need to defer to the release after 0.6.0 due to Appsody re-design.  The defer decision of the feature is under discussion.

**Comment by marikaj123** [comment]
According to Chunlong, There are 3 issues (endpoints) discussed in this epic.  Two of the threes have been resolved. One is not addressed, according to Tim Debor, there is a redesign in that area, and they decided not to fix it until the redesign. @jtmulvey  is Ok with the defer for this particular endpoint. Jim did say he will update the epic

**Comment by jtmulvey** [comment]
@stephenkinder @marikaj123 @chunlongliang-ibm @arobinson7532 @deboer-tim : As identified in our discussion yesterday, this issue is bigger than providing a secure endpoint for pulling collections (soon to be stacks) artifacts.  The file server that is used here is currently not setup in the cluster for authentication (not behind an oauth proxy). There are atleast two basic things to fix for this.
1) re-configure the web server to require secure connections (https) and authentication (behind oauth proxy)
2) identify and update ALL clients that are now using the server to ensure they provide credentials and accept the returned self-signed certificate
I will get a group of us together to review a design for this and work out who's doing what and when- and create the child issues.

**Comment by tseelbach** [comment]
The Kabanero CLI / REST service Route currently uses tls.termination: passthrough.  We think it should be reencrypt , because if every service (landing, cli, what else?) uses passthrough they would each have unique certificate requirements.

Or, if customers require choice of passthrough, reencrypt, and perhaps edge then we need to know that as well.  

These security choices should be made at install time for Kabanero as part of overall security strategy and not as a unique experience for the CLI / REST service

Does this issue / design cover the above?

**Comment by tseelbach** [comment]
To answer my question. No this issue does not cover tls.termination for CLI service.   I moved it to separate issue - see https://github.com/kabanero-io/kabanero-security/issues/70

**Comment by marikaj123** [comment]
Closing the feature since the design review is complete now.
