### ISSUE TITLE
Serverless -  1.5.0

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#147]
Find out if we need to move to a new version or Serverless

**Comment by marikaj123** [comment]
@garypicher - Do we need to move to a new level for Kabanero 0.9.0?

**Comment by garypicher** [comment]
Serverless is still in tech preview, and so I don't think it's imperative to move up.  Once it leaves tech preview, we will want to start obtaining it from the RedHat catalog.

**Comment by erpenbach** [comment]
@garypicher based upon the effort to adopt newer levels of Serverless in the past, would it be "low" effort to stay as current as possible?  Any idea on the extend of changes already in the latest levels?  This could reduce the amount of work later.

**Comment by kaczyns** [comment]
We've been trying to stay current, as that's the only way we can hope to get support from Red Hat if a Kabanero user has trouble.  From the Serverless operator's perspective, the user doesn't get to pick which version of the Serverless operator they install - they get what is currently available in the catalog.

**Comment by garypicher** [comment]
@erpenbach The reason that I didn't want to move is because tech preview releases can introduce incompatible changes and that has bitten us in the past.  So my thinking is that we wouldn't move unless there's a compelling reason to.

There's probably some value in moving up in smaller steps because it allows us to get fixes sooner, however I'm not sure that it saves work overall.  In other words, moving each incremental step might take X person-days, but moving up 3 incremental steps all at once probably takes less than 3X person-days, maybe 2.5X person-days, so the overall effort is probably greater to do it in small steps.  If teams are time pressured already, it makes sense to put it off.

That being said, if teams have some time, there's value in moving up because RedHat won't support us if we hit problem on something other than the current version, so if a customer hit a problem that was caused by a serverless bug, we'd need to create on the current version.

Currently, we are on OCP Serverless 1.5.0, and we *could* move to 1.6.0.  The changes are described here:

https://docs.openshift.com/container-platform/4.3/serverless/serverless-release-notes.html

In general, staying current is the right thing if we have cycles to do it, but there's no specific reason for us to do so, so it probably just depends on if we have the time.
