### ISSUE TITLE
java-microprofile collection pipeline doesn't complete

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/roadmap#64]
Fails with message

2019/08/29 17:20:56 ImageResource docker-image doesn't have an index.json file: stat /workspace/builtImage/index.json: no such file or directory
2019/08/29 17:20:56 Image digest exporter output: [] 

from this code

https://github.com/tektoncd/pipeline/blob/v0.5.2/cmd/imagedigestexporter/main.go#L55

0.1.0 kabanero release
v0.5.2 tekton

manual run script
https://github.com/dacleyra/kabanero-foundation/blob/0.1.0/scripts/appsody-tekton-example-manual-run.sh

**Comment by kvijai82** [comment]
The messages itself are new messages due to additional logging that was added in Tekton.  They don't seem to be affecting running of the pipelines itself and seem to be noise.  We were able to install the latest kabanero foundation using the install script and drive the pipelines to conclusion both manually and via webhooks.

**Comment by dacleyra** [comment]
able to complete pipelinerun

**Comment by tseelbach** [comment]
At a minimum the message should be [INFO] .  Perhaps open an issue on tekton and ask them to fix the message.  Indicate that its informational.

**Comment by tseelbach** [comment]
i removed the release-0.1 label since Dan indicated code works 7.   
I reopened yesterday so we could improve messaging so we don't get customer support tickets.
