### ISSUE TITLE
Install and run Kabanero Foundation on OpenShift 4.2

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/roadmap#91]
OpenShift 4.2 GA's early in the 0.3.0 lifecycle, however, there are daily builds we can use to get started in the interim.  

This initial support is limited to x86 architecture.

Important work items related to this are:

1) New OpenShift install script.
1) Appsody, kAppNav, and Kabanero operators as managed by OLM.
1) Leverage built-in components of OpenShift, a.k.a. ServiceMesh.
1) Retest Kabanero.

**Comment by csantanapr** [comment]
>3. Leverage built-in components of OpenShift, a.k.a. ServiceMesh.

There are other components provided by OpenShift 4.2 other than ServiceMesh Operator GA, that kabanero should leverage 
- OpenShift Serverless Operator (knative) provided by RedHat
- OpenShift Pipeline Operator (tekton) provided by RedHat

**Comment by kaczyns** [comment]
I plan on coming to the architecture board next week to discuss what the Kab operator team has been working on WRT getting to OCP 4.2 and OLM.  A quick summary of where we are at:

1) Dependency resolution (ie kab operator depends on xyz operators) in the CSV does not work as we expected.  We have an issue open against operator-lifecycle-manager which they are addressing, but it's likely not going to be fixed until OCP 4.3.
2) Subscribing to the individual operators in a specific catalog works.  There is no good way to force to a specific version which makes co-reqs between specific versions of operators difficult.
3) There is a desire to use the Red Hat approved/supported variants where possible.  This means OpenShift Service Mesh instead of Istio, and OpenShift Serverless instead of Knative Serving.
4) Some operators with OpenShift in the name (like OpenShift Pipeline Operator) are still in the community-operators catalog, and while they are provided by Red Hat, they are not approved/supported yet.

Our primary objective at this point is getting a combination of operators that are compatible with each other.  Specifically, the following dependencies are noted:
1) The Tekton dashboard and webhook v0.2 requires the OpenShift Pipelines Operator v0.7, and compatible versions of the Knative components to support the Github webhook.  This may just be a point-in-time statement.
2) Appsody supports deploying applications to Knative, but is more flexible on which version of Knative we use (only requires Knative Serving).

To that end, Adam has done some work to sort out versions that are compatible with the Tekton dashboard and webhook, and has the following working document reporting what he's found and how to install it:
https://github.com/a-roberts/openshift42/blob/master/README.md

For Kabanero 0.3.0, we are currently recommending the following:
1) OpenShift Service Mesh v1.0.1 from redhat-operators
2) OpenShift Serverless v1.1.0 from redhat-operators (not available yet)
3) Knative Eventing v0.8 from community-operators
4) Knative Eventing-contrib v0.8 installed manually by the Kab operator (no OLM install available)
5) OpenShift Pipelines v0.7.0 from community-operators
6) Appsody v0.2.0 from certified-operators
7) Kabanero v0.3.0 from TBD (certified-operators, community-operators, or private catalog)

with the following caveats:
1) It will be difficult, if not impossible, to "hold" the versions of these operators where they are.  OLM will attempt to upgrade them as upgrades become available in the catalog/channel which they are obtained from
2) The dependency on Knative Eventing and Knative Eventing-contrib may be temporary, at which point the version co-reqs which are problematic go away
3) A "one-click install" from the OpenShift Operator Hub will be impossible, since subscriptions will need to be created manually for each dependent operator.  This can be accomplished via an install shell-script, as is done today for the non-OLM Kabanero foundation install.
4) There is still work to do to verify the end-to-end path of creating a Tekton webhook, triggering a PR thru deploying an application via Appsody-operator.  However we are optimistic that things are going to be OK.

When we get to OCP 4.3, we can re-evaluate whether a one-click install is possible, assuming the issues around operator dependency resolution are fixed.
